### ISSUE TITLE
[SSV V1.7] A/E PFD doesn't reflect true state of DAP mode in MM104/105

### ISSUE THREAD

**Issue by daves-ssu** [GLS-SSV/SSV#17] opened 2023-09-05 19:41 UTC
When in MM104/MM105, the A/E PFD DAP Mode doesn't show the true state of the DAP, always showing AUTO even if the DAP is in INRTL or LVLH. Attached a screenshot showing this, DAP PBIs on C3 show the DAP in INRTL as it should be right after the pitch-around for photos of the ET, while the A/E PFD is stuck in AUTO for the DAP mode.
![SSV_AE_PFD_DAP_mode_error](https://github.com/GLS-SSV/SSV/assets/107274810/7df15ee6-281c-4849-93b3-118275af5558)

**Comment by GLS-SSV** [comment] 2024-01-22 10:26
Currently, one could say that there is no TransDAP implemented, so this is not a bug, but is instead a result of that.
In any case, the TransDAP will probably have a (proper) implementation in the OMSRCS branch, and the correct MEDS "signal" to control that display parameter is being implemented in the GPC_IDP_interface branch.
So I'm closing this, as there is nothing specific to work on, and the issue will go away in the near future.

**Closed as completed by GLS-SSV** 2024-01-22 10:26 UTC
